# Generated by Django 5.2.8 on 2025-11-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
