# Generated by Django 5.2.6 on 2025-12-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_review_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('piece', 'Pièce'), ('liter', 'Litre'), ('bunch', 'Botte'), ('bag', 'Sac'), ('box', 'Boîte')], default='piece', help_text='Unité de vente', max_length=10),
        ),
    ]
