# Generated by Django 5.2.8 on 2025-11-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Latitude de l'emplacement du vendeur", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Longitude de l'emplacement du vendeur", null=True),
        ),
    ]
