# Generated by Django 5.2.6 on 2025-12-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_country',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
